Repository nearai/nearai, pull requests merged in 2025-02, with the labels that each got.

#791 Remove cryptography dependency version upper limit
  poetry.lock
  pyproject.toml
Labels: dependencies

#818 Update inference.md with model formats and expected usage
  docs/inference.md
Labels: documentation

#807 Fix 422 errors on empty messages when calling models with tools in langgraph functions
  hub/api/v1/completions.py
  nearai/openapi_client/api/agents_api.py
  nearai/openapi_client/api/agents_assistants_api.py
  nearai/openapi_client/models/create_thread_and_run_request.py
Labels: bug

#896 Fix env.completions_and_run_tools
  nearai/agents/environment.py
Labels: bug

#926 Update AGENT_KIT_TEMPLATE_AGENT_ID
  hub/demo/src/components/NewAgentButton.tsx
Labels: eth-denver-2025, framework

#927 Remove Max Iterations View
  hub/demo/src/components/AgentRunner.tsx
Labels: bug

#925 Update nearai_langchain and coinbase libraries for agentkit
  aws_runner/frameworks/requirements-agentkit.txt
Labels: eth-denver-2025, framework

#928 Add another row of resources at the bottom of a main page
  hub/demo/src/app/page.tsx
Labels: documentation, user interface, eth-denver-2025

#959 Modified Message content to Union[List, str]
  hub/api/v1/completions.py
Labels: enhancement, assistant-and-protocols, framework
